# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Quick Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x        
    - name: Restore
      run: dotnet restore src/Nfinity.Extensions.Pipes.sln      
    - name: Build
      run: dotnet build src/Nfinity.Extensions.Pipes.sln
          --no-restore
          --configuration Release
    - name: Test
      run: dotnet test src/Nfinity.Extensions.Pipes.Test
          --no-build
          --configuration Release
          --verbosity normal
